name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: slundi/rust-musl-docker-build-multi-arch
  PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ env.IMAGE }}:latest
#    - name: Build and push ARM64
#      run: docker buildx build --output "type=image,push=true" --platform=linux/arm64 --tag "${{ env.IMAGE }}:latest" .
#      with:
#        context: .
#        platform: linux/arm64
#        push: ${{ env.IMAGE }}:latest
#        tags: latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
